### PR TITLE
Infer shape of source space from target space

### PR DESCRIPTION
**Pull request by kclamar**
Hi,

I'm wondering if it's possible to allow transformations of coordinates when the target space has a shape but the source space doesn't?

### CODE REVIEW

**Comment by kclamar** [comment]
Hi @vigji,

Thanks for the response! In my workflow I save the coordinates of points in the "sal" space and sometimes I need to conversion the coordinates to the space of the mpin_zfish_1um atlas. When I initialize the source space for the conversion I need to calculate the shape of the atlas stack after transforming to the source space. I think it'd be convenient to have this new feature since the atlas space already contains the shape information. I also see why it could be dangerous, so I think that having a keyword argument for this feature and making it not the default behavior would be a good option.

**Review by vigji — COMMENTED** [review]
Awesome! 
This is good to go for me, would you mind just adding a little test for your addition in the tests module so that coverage is not decreased? It should be easy by looking at the rest of the tests in the module, but I can give more pointers if needed!

**Comment by kclamar** [comment]
I've added a test with axes flipping and reordering.

**Comment by vigji** [comment]
Awwwwwesome!  Thank you very much @kclamar !

**Comment by vigji** [comment]
will release a new version with this

**Pull request merged**
